version: '3'
services:
  poi:
    build:
      context: /src/poi
      dockerfile: /dockerfiles/Dockerfile_3
    image: tripinsights/poi:1
  trips:
    build:
      context: /src/trips
      dockerfile: /dockerfiles/Dockerfile_3
    image: tripinsights/trips:1
  user-java:
    build:
      context: /src/user-java
      dockerfile: /dockerfiles/Dockerfile_2
    image: tripinsights/user-java:1
  userprofile:
    build:
      context: /src/userprofile
      dockerfile: /dockerfiles/Dockerfile_2
    image: tripinsights/userprofile:1
  tripviewer:
    build:
      context: /src/tripviewer
      dockerfile: /dockerfiles/Dockerfile_1
    image: tripinsights/tripviewer:1
